---
title: "First codes + map"
author: "Tymoteusz Mętrak"
date: "2024-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries
```{r}
library(tidyr)
library(tidyverse)
library(sf) # simple features -> do map
library(dlookr) # do przyjemnej EDA
library(ggplot2)
library(ggthemes)
library(stringr) # do operacji na tekście
```

Reading the data
```{r}
getwd()
municipalities <- read.csv("data_municipalities.csv")
View(municipalities)
str(municipalities)

# Remove whitespaces from text variables and convert them to numeric
for (i in 1:ncol(municipalities)){
  municipalities[,i] <- str_remove_all(string = municipalities[,i], 
                                       pattern = "\\s")
}

for ( i in 4:ncol(municipalities)){
  municipalities[,i] <- as.numeric(municipalities[,i])
}
```


Other data reading
```{r}
counties <- read.csv("data_counties.csv")

gminy <- read_sf("shapefiles_wec/map_municipalities.shp")
colnames(gminy)[1] <- colnames(municipalities)[1]
colnames(municipalities)[1]
gminy$municipality_code <- as.numeric(gminy$municipality_code)

gminy <-  left_join(gminy, municipalities, by = join_by(municipality_code))

zabory <- read_sf("shapefiles_wec/map_partitions.shp")
```


Adjusting projections
```{r}
gminy <- st_transform(gminy, 4326)
zabory <- st_transform(zabory, 4326)
```


The map
```{r}
ggplot(gminy) +
  geom_sf(aes(fill=percent_vaccinated,col=percent_vaccinated)) +
  geom_sf(data = zabory, fill = NA, col = "red")+
  scale_fill_viridis_c()+
  guides(fill=guide_legend(title = "Vaccination \nrate"),
         color="none")+
  labs(title = "Vaccination rate in Poland",
       x="\n",
       y="\n")+
  theme_gdocs()
```

ZABORY
```{r}
#install.packages("secr")
library(secr)

crds <- st_centroid(gminy)
cords <- st_coordinates(crds)

Prussian <- zabory[zabory$partition=="prussian",] %>%
  as_Spatial()
Russian <- zabory[zabory$partition=="russian",] %>%
  as_Spatial()
Austrian <- zabory[zabory$partition=="austrian",] %>%
  as_Spatial()

municipalities$Prussian <- pointsInPolygon(cords, Prussian)
municipalities$Russian <- pointsInPolygon(cords, Russian)
municipalities$Austrian <- pointsInPolygon(cords, Austrian)

for (i in 1:nrow(municipalities)){
  if (municipalities[i,"Prussian"]==TRUE){
    municipalities[i,"Prussian"] <- 1
  }
  else if (municipalities[i,"Prussian"]==FALSE){
    municipalities[i,"Prussian"] <- 0
  }
  if (municipalities[i,"Russian"]==TRUE){
    municipalities[i,"Russian"] <- 1
  }
  else if (municipalities[i,"Russian"]==FALSE){
    municipalities[i,"Russian"] <- 0
  }  
  if (municipalities[i,"Austrian"]==TRUE){
    municipalities[i,"Austrian"] <- 1
  }
  else if (municipalities[i,"Austrian"]==FALSE){
    municipalities[i,"Austrian"] <- 0
  }
}

write.csv(municipalities, file = "municipalities_enhanced_2.csv")

```

