# rr_spatial_model


```{r}

library(sf)
library(tidyverse)
library(sp)
library(spdep)
library(SpatialRDD)
```


```{r}
data_full_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\datamaster_final_full.xlsx)"
data_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\datamaster_final.xlsx)"
data <- readxl::read_xlsx(data_path)
data_full <- readxl::read_xlsx(data_full_path)
```

## Mapa

```{r}
setwd(r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\_data\shapefile)")
map_municipalitties <- read_sf(".", "map_municipalities") %>% 
	mutate(mncplty_c = as.numeric(mncplty_c))
map_municipalitties<- st_transform(map_municipalitties, "+proj=longlat")
colnames(map_municipalitties)
```

```{r}
setwd(r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\_data\shapefile)")
map_partitions <- read_sf(".", "map_partitions") 
map_partitions <- st_transform(map_partitions, "+proj=longlat")
plot(map_partitions)
common_border <- st_intersection(map_partitions$russian, map_partitions$prussian)

```



```{r}
dane.przestrzenne <- data %>% 
	inner_join(map_municipalitties, by = c("municipality_code" = "mncplty_c")) %>% 
	mutate(kod = municipality_code) %>% 
	mutate(id = 1:nrow(.))


polygon_full <-  st_as_sf(st_union(map_partitions$geometry))
cut_off <- st_as_sf(st_cast(map_partitions$geometry[2], "MULTILINESTRING"))
border <- st_as_sf(st_cast(polygon_full, "MULTILINESTRING"))
# others <- st_as_sf(st_intersection(map_partitions$geometry[1], map_partitions$geometry[3]))
# cut_off = st_difference(cut_off, border)
# others <- st_difference(cut_off, others)
# empty_points <- st_is_empty(cut_off)

# cut_off <- st_multilinestring(st_linestring(cut_off[[1]][[1]][[12]]))

polygon_treated <- st_as_sf(map_partitions$geometry[2])

```


```{r}

library(tmap)
tm_shape(polygon_full) + tm_polygons() + 
  tm_shape(polygon_treated) + tm_polygons(col = "grey") + 
  tm_shape(cut_off) + tm_lines(col = "red")

```


```{r}
points_samp.sf <-  st_centroid(dane.przestrzenne$geometry)

points_samp.sf <- sf::st_sf(points_samp.sf) # make it an sf object bc st_sample only created the geometry list-column (sfc)
points_samp.sf$id <- 1:nrow(points_samp.sf) # add a unique ID to each observation
# visualise results together with the line that represents our RDD cutoff
tm_shape(points_samp.sf) + tm_dots() + tm_shape(cut_off) + tm_lines(col = "red")

```
```{r}
points_samp.sf$treated <- assign_treated(points_samp.sf, polygon_treated, id = "id")
tm_shape(points_samp.sf) + tm_dots("treated", palette = "Set1") + tm_shape(cut_off) + tm_lines(col = "red")
```
```{r}

data_rdd <- points_samp.sf %>% 
	inner_join(dane.przestrzenne)
list(lm(percent_vaccinated ~ Prussian, data = data_rdd)) %>% 
	stargazer::stargazer(type = "text")
```
```{r}
data_rdd$dist2cutoff <- as.numeric(sf::st_distance(points_samp.sf, cut_off))
data_rdd$dist2border <- as.numeric(sf::st_distance(points_samp.sf, border))

# data_rdd$dist2cutoff < 2000 & !data_rdd$dist2border < 1000


# Define your plot
plot <- tm_shape(data_rdd[data_rdd$dist2cutoff < 15000 & !data_rdd$dist2border < 15000, ]) + 
  tm_dots("percent_vaccinated", palette = "RdYlGn", size = .1) + 
  tm_shape(cut_off) + tm_lines()

# Customize the layout
plot <- plot + tm_layout(
  legend.outside = FALSE,  
  legend.position = c("right", "bottom"),
  inner.margins = c(0.05, 0.05, 0.05, 0.05),  # Adjust inner margins
  outer.margins = c(0.1, 0.1, 0.1, 0.1),      # Adjust outer margins
  legend.text.size = 1.2,                    # Adjust legend text size
  title.position = c("center", "top"),       # Position of the title
  title.size = 1.5,                          # Adjust title size
  title.color = "black"                    # Set font to Times New Roman
)


# Display the plot
plot
```


```{r}
rdds <- map(seq(from = 2000, to =20000, by = 2000),
				  .f =~lm(percent_vaccinated ~ Prussian, data = data_rdd[data_rdd$dist2cutoff < .x & !data_rdd$dist2border < .x, ]))
results <- map2(rdds,seq(from = 2000, to =20000, by = 2000), .f = ~broom::tidy(.x) %>% 
					 	bind_cols(cutoff = .y, n = .x$df.residual)) %>% 
	bind_rows()

results
```
