### Data processing

```{r }
# setwd("C:/Users/rados/OneDrive - SGH/WarsawEconometricChallenge/WarsawEconometricChallenge")

list.files("C:/Users/rados/OneDrive - SGH/WarsawEconometricChallenge/WarsawEconometricChallenge/_data")
data_counties_path = r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\_data\data_counties.csv)"
data_municipalities_path = r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\_data\data_municipalities.csv)"
data_municipalities_enhanced_path= r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\1_raw_data\municipalities_enhanced_2.csv)"
```

## Libraries

```{r}
library(tidyverse)
library(sf) # simple features -> do map
library(dlookr) # do przyjemnej EDA
library(ggthemes)
library(naniar)

```

## Download data

```{r}

data_counties <- read.csv(data_counties_path)
data_municipalities <- read.csv(data_municipalities_enhanced_path)

```

## Check NA

```{r}

# data_counties %>% 
# 	keep(.p = is.numeric) %>% 
# 	select(-county_code) %>% 
# 	imap(.f = ~ggplot(data.frame(x = .x)) +
# 			 	geom_histogram(aes(x = x)) +
# 			 	labs(x = .y))


```

```{r}


# data_municipalities %>%
# 	keep(.p = is.numeric) %>%
# 	select(-contains("population"), -municipality_code, -county_code) %>%
# 	imap(.f = ~ggplot(data.frame(x = .x)) +
# 			 	geom_histogram(aes(x = x)) +
# 			 	labs(x = .y))
```

```{r}
data_municipalities %>% 
	select(where(~any(is.na(.x)))) %>% 
	map(.f = ~sum(is.na(.x)))

```

```{r}
data_counties %>% 
	select(where(~any(is.na(.x)))) %>% 
	map(.f = ~sum(is.na(.x)))
```

## Wybory

```{r}
wybory_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\1_raw_data\wyniki_gl_na_listy_po_gminach_proc_sejm.csv)"
dict_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\dict_master.xlsx)"

dict <- readxl::read_xlsx(dict_path)
wybory_raw <- read.csv2(wybory_path)

colnames(wybory_raw) %>% 
	glue::glue_collapse("\n")
```

```{r}

colnames_wybory <- tibble(colnames = colnames(wybory_raw)) %>% 
	left_join(dict, by = c("colnames" = "variable_name")) %>% 
	select(new_label) %>% 
	unlist() %>% 
	unname()


wybory_df <- wybory_raw 

	
colnames(wybory_df) <- colnames_wybory


	
wybory_df
```

## Agregacja population

```{r}

# colnames(data_gminy)
data_population <- data_municipalities %>% 
	mutate(teryt_gmina = str_remove(municipality_code, "(.{1})$")) %>%
	mutate(teryt_gmina = as.integer(teryt_gmina)) %>% 
	select(teryt_gmina, matches("population")) %>% 
	pivot_longer(-teryt_gmina) %>% 
	mutate(name = str_remove_all(name, "population_|total_")) %>% 
	filter(!str_detect(name, "density|per_pharmacy")) %>% 
	tidyr::extract(col = name, regex = "(\\d{1,2})_(\\d{1,2})", into = c("lower","upper"), remove = FALSE) %>% 
	mutate(name = str_remove_all(name, "\\d|_")) %>% 
	mutate(population_base = ifelse(name == "total" & is.na(lower), value, NA)) %>% 
	group_by(teryt_gmina) %>% 
	fill(population_base, .direction = "downup") %>% 
	drop_na() %>% 
	mutate(name = ifelse(name == "total", "t", name))

data_population_new <- data_population %>% 
	mutate(value = value/population_base) %>% 
	# group_by(name, teryt_gmina) %>% 
	# summarize(sum(value))
	unite(c(name, lower, upper), col = "name") %>% 
	mutate(name = paste0("pop_",name,"_perc")) %>% 
	select(-population_base) %>% 
	pivot_wider()

data_population_sex <- data_population %>% 
	ungroup() %>% 
	group_by(teryt_gmina, name) %>% 
	mutate(value = sum(value)) %>% 
	mutate(value = value/population_base) %>%
	select(-c(lower, upper, population_base)) %>% 
	distinct() %>% 
	mutate(name = paste0("pop_",name,"_all_perc")) %>% 
	pivot_wider() %>% 
	select(-pop_t_all_perc)
```

```{r}

data_population_newgroups <- data_population %>% 
	mutate(new_lower = case_when(
		lower < 20 ~ 0,
		lower < 30 ~ 20,
		lower < 40 ~ 30,
		lower < 50 ~ 40,
		lower < 60 ~ 50,
		.default = 60
	)) %>% 
	mutate(new_upper = case_when(
		lower < 20 ~ 19,
		lower < 30 ~ 29,
		lower < 40 ~ 39,
		lower < 50 ~ 49,
		lower < 60 ~ 59,
		.default = 84
	)) %>% 
	unite(c(name, new_lower, new_upper), col = "name") %>% 
	ungroup() %>% 
	group_by(name, teryt_gmina) %>% 
	mutate(value = sum(value)) %>% 
	mutate(value = value/population_base) %>% 
	select(-c(population_base, lower, upper)) %>% 
	distinct() %>%
	mutate(name = paste0("pop_",name,"_perc")) %>%
	pivot_wider()
	

```

```{r}
data_municipalities %>% 
	select(where(~any(is.na(.x)))) %>% 
	map(.f = ~sum(is.na(.x)))

```

## BDL new data

```{r}

bdl_new_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\2_data_processing\bdl\data_bdl_wec.xlsx)"

bdl_new_raw <- readxl::read_xlsx(bdl_new_path)
```
```{r}
bdl_new <- bdl_new_raw %>% 
	filter(!str_detect(name, "obszar wiejski| - miasto") ) %>%
	filter(podatek_rolny != 0 | name == "Hel" | name == "Jastarnia") %>% 
	mutate(kod = as.integer(kod))
```
## 
Data Wojtek 

```{r}

counties_exposure_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\1_raw_data\data_counties_exposure.csv)"
index_ineq_path  <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\1_raw_data\data_index_ineq.csv)"
muni_exposure_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\1_raw_data\data_muni_exposure.csv)"

index_ineq_raw <- read.csv(index_ineq_path) %>% 
	select(-X)
counties_exposure_raw <- read.csv(counties_exposure_path) 
muni_exposure_raw <- read.csv(muni_exposure_path)

counties_exposure <- counties_exposure_raw %>% 
	select(county_code, EXP, high_exposure)

muni_exposure <- muni_exposure_raw %>% 
	select(municipality_code, high_exposure)


```

## Final

```{r}

mapping <- data_municipalities %>% 
	distinct(municipality_code, county_code, municipality_name)
data_powiaty <- data_counties %>% 
	left_join(mapping)
	
```


```{r}
data_gminy <- data_municipalities %>% 
	mutate(teryt_gmina = str_remove(municipality_code, "(.{1})$")) %>%
	mutate(teryt_gmina = as.integer(teryt_gmina)) %>% 
	inner_join(wybory_df, by = c("teryt_gmina" = "kod_teryt")) %>% 
	inner_join(data_population_new, by = "teryt_gmina") %>% 
	inner_join(data_population_newgroups, by = "teryt_gmina") %>% 
	inner_join(data_population_sex, by = "teryt_gmina") %>% 
	inner_join(bdl_new, by = c("teryt_gmina" = "kod")) %>% 
	inner_join(muni_exposure, by = "municipality_code") %>% 
	inner_join(index_ineq_raw, by = "municipality_code")  %>% 
	inner_join(data_powiaty) %>% 
	group_by(county_code) %>% 
	mutate(across(
		.cols = c(healthcare_advices,forests_area,
					 children_3_5_in_kindergartens, 
					 high_exposure,
					 tourits_per_1000_persons),
		.fns = ~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))) %>% 
	ungroup() %>% 
	mutate(across(
		.cols = c(healthcare_advices,forests_area,
					 children_3_5_in_kindergartens, 
					 high_exposure,
					 tourits_per_1000_persons),
		.fns = ~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x))) %>% 
	select(!where(~any(is.na(.x)))) %>% 
	select(-X) %>% 
	mutate(population_total_log = log(population_total))# wywalamy na

data_gminy %>%
	select(where(~any(is.na(.x)))) %>%
	# filter(is.na(forests_area))
	map(.f = ~sum(is.na(.x)))
```
```{r}

dict_final <- tibble(colnames = colnames(data_gminy)) 
```

```{r}
list_data <- list(municipalities = data_gminy)

writexl::write_xlsx(list_data, "data_master.xlsx")


```
