## Final database

```{r}
library(tidyverse)
library(readxl)

setwd("C:/Users/rados/OneDrive - SGH/WarsawEconometricChallenge/WarsawEconometricChallenge/2_data_processing")
datamaster_kol_path <- "data_master_kolorowy.xlsx"
datamaster_path <- r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\2_data_processing\data_master.xlsx)"

data_master_raw <- readxl::read_xlsx(datamaster_path)
data_master_kol <- readxl::read_xlsx(datamaster_kol_path )

colnames(data_master_raw)
```
```{r}
data_master <- data_master_raw %>% 
	select(c(colnames(data_master_kol), "unemployment_50", "unemployment_25", area_km2, population_total, population_total_log)) %>%  
	# mutate(home_appliances =  (installations_toilet +
	# 								  	installations_bathroom	+
	# 								  	installations_central_heating +
	# 								  	installations_network_gas +
	# 								  	installations_watersupply)) %>%
	mutate(rolny_revenue_ratio = (podatek_rolny/exp(population_total_log))/revenues_per_capita) %>% 
	mutate(unemployment_25 = unemployment_25/exp(population_total_log)) %>% 
	mutate(unemployment_50 = unemployment_50/exp(population_total_log)) %>% 
	# select(-c(installations_toilet,installations_bathroom,
	# 			 installations_central_heating,installations_network_gas, installations_watersupply)) %>% 
	select(-c("unemployed_up_to_25", "unemployed_over_50" ,"unemployed_long_term")) %>% 
	select(-c(podatek_rolny, appartment_area_per_person, unemployment_rate,
				 population_per_pharmacy, revenues_per_capita, net_scholarization, 
				 appartments_per_1000_persons, population_density)) %>% 
	mutate(last_n = str_extract(municipality_code, ".$")) %>% 
	mutate(type_1 = case_when(
		last_n == 1 ~ "urban",
		last_n == 2 ~ "rural",
		.default = "mixed"
	)) %>% 
	mutate(type = case_when(
		type_1 == "rural" ~ "agr",
		population_total < 20000 & type_1 != "rural" ~ "0_20k",
		population_total < 50000 ~ "20_50k",
		population_total < 100000 ~ "50_100k",
		population_total < 500000 ~ "100_500k",
		.default = "500k+"
	)) %>% 
	mutate(ones =  1)  %>% 
	pivot_wider(names_from = type,
					values_from = ones,
					names_glue = "type_{type}") %>% 
	select(-c(last_n, population_total, type_1, glosy_PIS, pop_t_30_39_perc, type_20_50k, 
				 persons_running_business, education_share_primary, installations_bathroom)) %>% 
	replace_na(replace = list(type_agr = 0,
									  type_0_20k = 0,
									  type_50_100k = 0,
									  type_100_500k = 0,
									  `type_500k+` = 0)) 



```

```{r}
colnames(data_master)
```
```{r}


library(sf)
setwd(r"(C:\Users\rados\OneDrive - SGH\WarsawEconometricChallenge\WarsawEconometricChallenge\_data\shapefile)")
map_municipalitties <- read_sf(".", "map_municipalities") %>% 
	mutate(mncplty_c = as.numeric(mncplty_c))
map_municipalitties<- st_transform(map_municipalitties, "+proj=longlat")


dane.przestrzenne <- data_master %>% 
	inner_join(map_municipalitties, by = c("municipality_code" = "mncplty_c")) 

## long and lat
centroids <- st_centroid(dane.przestrzenne$geometry) %>% 
             unlist() %>%
             matrix(nrow = nrow(dane.przestrzenne), ncol = 2, byrow = TRUE)
dane.przestrzenne$long <- centroids[,1]
dane.przestrzenne$lat <- centroids[,2]

dane.przestrzenne <- dane.przestrzenne %>%  
	as.data.frame() %>% 
	select(-c(geometry, mncplty_s))

colnames(dane.przestrzenne)
```


```{r}

new_dict <- tibble(variable_name = colnames(data_master_raw)) %>% 
				full_join(tibble(variable_name = colnames(data_master), included = 1))



writexl::write_xlsx(new_dict, "new_dict.xlsx")

glue::glue_collapse("\n")
```
```{r}
writexl::write_xlsx(dane.przestrzenne,"C:/Users/rados/OneDrive - SGH/WarsawEconometricChallenge/WarsawEconometricChallenge/datamaster_final.xlsx")
```




